### ISSUE TITLE
[Feature/Enhancement]Make damage of lightsabers be configurable?

### ISSUE THREAD

**Issue by SteelShot** [FiskFille/AdvancedLightsabers#14]
As the title says, can/would you be able to make the damage to be able to be configured.
Why i'm asking is because the mod itself is awesome, but when it is places in a tech based pack or just installed along side tech mods specially with high end mods, it phazes out, just because the damage is too low. While it still hits a nice amout of damage, people in my server crafted few blades, showed em off, and now their just sitting in tools chests.

I myself could code it, but i'd have to learn Forge and i have no time for that at this momment, specialy when i need to prepare for UNI studies next year.

I think the feature shouldn't be too hard to code, it doesn't seem to complicated.
It could be something like 
I:"Light Saber Damage"=8 [Default value: 8]
or even be a multiplier to base damage:
S:"Light Saber Base Damage Multiplier"=1.0 [Default value: 1, Saber Damage 8 *1 = 8]

This is not required, but would make the mod compete with high end tool mods.

**Comment by Nova001Sol** [comment]
This. The big issue I have with the sabers is that, by the time players get 'em, they're obsolete. You don't even NEED any mods for that, vanilla sharpness on a diamond sword can easily outmatch a saber. With sharpness V, which isn't that hard to get, a diamond sword can deal 10 damage, a heart more than a saber.

And besides, a cow survives being hit by a high-tech laser sword? Really?

**Comment by FiskFille** [comment]
The lightsaber itself is fairly aesthetic, at the moment. We have a lot of cool stuff planned for the mod in the future, some of which just didn't make it into the initial release due to time constraints. The lightsaber will get buffed, I can assure you that much. While you wait, have a teaser:

![screenshot_1](https://cloud.githubusercontent.com/assets/10811084/15277191/e121c8da-1afc-11e6-8950-ec9eefad9d6b.png)
