### ISSUE TITLE
Client Crash (on server)

### ISSUE THREAD

**Issue by Cronosus** [FiskFille/AdvancedLightsabers#16]
on server, when i get lightsaber from creative, client crash (rightclick in NEI to give)
http://pastebin.com/mx274Azd

server say this:
http://pastebin.com/zxaEP17M

**Comment by SteelShot** [comment]
The server uses Kcauldron, it is know to cause a ton of errors, as they modifly a lot of how to put it "core classes" i dont have a better name. So a fix might be on their side.

**Comment by FiskFille** [comment]
This is due to NEI using the /give command for giving a player an item. Unfortunately, that also means it's limited to Minecraft's chat character limit.
Lightsabers use NBT data to store all of their properties, meaning they'll have a pretty long NBT tag string. As a result of this, the command executed by NEI becomes (for example)
`/give <player> lightsabers:lightsaber 1 0 {Parts:{emitter:"Graflex",switch_sec`
rather than the command with the full NBT tag, resulting in the crash.

Unfortunately, there isn't really anything I can do about this.

**Comment by SteelShot** [comment]
Interesting, why then i dont crash? I've tried all the sabers, i can spawn em perfecly....

**Comment by FiskFille** [comment]
NEI only utilizes the /give command on servers, to ensure the player only gets the item if they can give themselves items without the mod's help.

**Comment by Cronosus** [comment]
It crash only client, but only when click in nei on it to give, i warn my teammembers to not use nei for give, only creative menu.
I can't use forge server, we need some plugins like scripts, variable triggers, login protection plugins... forge server is useless for this.
but thanks for info.

**Comment by SteelShot** [comment]
Forge Essentials Features(Modules)
        B:Afterlife=DeathChests
        B:AuthLogin=Login Protection(validation)
        B:Backups=Backups
        B:Chat=Chat
        B:Commands=TPS,GOD, noclipc ect
        B:Economy=Economy
        B:Multiworld=Multi World
        B:PlayerLogger=Logs player changes, rols back reqions and such
        B:Remote=Dunno about this one
        B:Scripting=Scripts
        B:ServerVote=Votes
        B:SignTools=Sign commands
        B:Teleport=Teleportation
        B:Tickets=Suppor tickets(contact admin feature ish)
        B:WEIntegrationTools=World Edit that
        B:WorldBorder=World Border
        B:factions=Factions
        B:mapper=Dont know about this one
        B:perftools=Performance tools i guess

Everything can be disabled if not required.

**Comment by Cronosus** [comment]
still not enought, 9 plugins which we use not there..
as i say, for me is forgeserver useless
